<?php


namespace InvoiceXpress;

class Constants
{
    public const SEARCH_BY_CODE = 'code';
    public const SEARCH_BY_NAME = 'name';

    # Date Format Standard
    public const DATE_FORMAT = 'dd/mm/yyyy';
    # Date Format Standard
    public const DATE_FORMAT_CARBON = 'd/m/Y';

    # Generic yes or no
    public const ACCEPTED = 1;
    public const DENIED = 0;

    # Languages as country codes available for account UI
    public const LANGUAGE_PT = 'pt';
    public const LANGUAGE_EN = 'en';
    public const LANGUAGE_ES = 'en';

    public const ACCOUNT_LANGUAGES = [
        self::LANGUAGE_PT,
        self::LANGUAGE_EN,
        self::LANGUAGE_ES,
    ];

    # Used for clients, to define how much is the maturity day for this costumer invoices
    # This value also can be a custom value in DAYS. We just preconfigured here for meh, documentation wise.
    public const CLIENT_PAYMENT_DAYS_NONE = 0;
    public const CLIENT_PAYMENT_DAYS_15 = 15;
    public const CLIENT_PAYMENT_DAYS_30 = 30;
    public const CLIENT_PAYMENT_DAYS_45 = 45;
    public const CLIENT_PAYMENT_DAYS_60 = 60;
    public const CLIENT_PAYMENT_DAYS_90 = 90;

    public const CLIENT_PAYMENT_DAYS = [
        self::CLIENT_PAYMENT_DAYS_NONE => self::CLIENT_PAYMENT_DAYS_NONE,
        self::CLIENT_PAYMENT_DAYS_15 => self::CLIENT_PAYMENT_DAYS_15,
        self::CLIENT_PAYMENT_DAYS_30 => self::CLIENT_PAYMENT_DAYS_30,
        self::CLIENT_PAYMENT_DAYS_45 => self::CLIENT_PAYMENT_DAYS_45,
        self::CLIENT_PAYMENT_DAYS_60 => self::CLIENT_PAYMENT_DAYS_60,
        self::CLIENT_PAYMENT_DAYS_90 => self::CLIENT_PAYMENT_DAYS_90,
    ];

    ## Payment methods
    public const PAYMENT_METHOD_CREDIT_CARD = 'CC';
    public const PAYMENT_METHOD_DEBIT_CARD = 'CD';
    public const PAYMENT_METHOD_BANK_CHECK = 'CH';
    public const PAYMENT_METHOD_CHECK_VOUCHER = 'CO';
    public const PAYMENT_METHOD_BALANCE = 'CS';
    public const PAYMENT_METHOD_ELECTRONIC_CASH = 'DE';
    public const PAYMENT_METHOD_COMMERCIAL_PAPER = 'LC';
    public const PAYMENT_METHOD_MULTIBANCO = 'MB';
    public const PAYMENT_METHOD_CASH = 'NU';
    public const PAYMENT_METHOD_OTHER = 'OU';
    public const PAYMENT_METHOD_EXCHANGE_PROPERTIES = 'PR';
    public const PAYMENT_METHOD_BANK_TRANSFER = 'TB';
    public const PAYMENT_METHOD_RESTAURANT_TICKET = 'TR';

    public const PAYMENT_METHODS = [
        self::PAYMENT_METHOD_CREDIT_CARD => self::PAYMENT_METHOD_CREDIT_CARD,
        self::PAYMENT_METHOD_DEBIT_CARD => self::PAYMENT_METHOD_DEBIT_CARD,
        self::PAYMENT_METHOD_BANK_CHECK => self::PAYMENT_METHOD_BANK_CHECK,
        self::PAYMENT_METHOD_CHECK_VOUCHER => self::PAYMENT_METHOD_CHECK_VOUCHER,
        self::PAYMENT_METHOD_BALANCE => self::PAYMENT_METHOD_BALANCE,
        self::PAYMENT_METHOD_ELECTRONIC_CASH => self::PAYMENT_METHOD_ELECTRONIC_CASH,
        self::PAYMENT_METHOD_COMMERCIAL_PAPER => self::PAYMENT_METHOD_COMMERCIAL_PAPER,
        self::PAYMENT_METHOD_MULTIBANCO => self::PAYMENT_METHOD_MULTIBANCO,
        self::PAYMENT_METHOD_CASH => self::PAYMENT_METHOD_CASH,
        self::PAYMENT_METHOD_OTHER => self::PAYMENT_METHOD_OTHER,
        self::PAYMENT_METHOD_EXCHANGE_PROPERTIES => self::PAYMENT_METHOD_EXCHANGE_PROPERTIES,
        self::PAYMENT_METHOD_BANK_TRANSFER => self::PAYMENT_METHOD_BANK_TRANSFER,
        self::PAYMENT_METHOD_RESTAURANT_TICKET => self::PAYMENT_METHOD_RESTAURANT_TICKET,
    ];

    # List of countries. You may update this list by using the StringUtil::lines_to_constants($text)
    # By passing the line of countries given by Invoice Express
    public const COUNTRY_PORTUGAL = 'Portugal';
    public const COUNTRY_IRELAND = 'Ireland';
    public const COUNTRY_UK = 'UK';
    public const COUNTRY_CANADA = 'Canada';
    public const COUNTRY_UNITED_STATES = 'United States';
    public const COUNTRY_AFGHANISTAN = 'Afghanistan';
    public const COUNTRY_ALBANIA = 'Albania';
    public const COUNTRY_ALGERIA = 'Algeria';
    public const COUNTRY_AMERICAN_SAMOA = 'American Samoa';
    public const COUNTRY_ANDORRA = 'Andorra';
    public const COUNTRY_ANGOLA = 'Angola';
    public const COUNTRY_ANGUILLA = 'Anguilla';
    public const COUNTRY_ANTIGUAAND_BARBUDA = 'Antigua and Barbuda';
    public const COUNTRY_ARGENTINA = 'Argentina';
    public const COUNTRY_ARMENIA = 'Armenia';
    public const COUNTRY_ARUBA = 'Aruba';
    public const COUNTRY_AUSTRALIA = 'Australia';
    public const COUNTRY_AUSTRIA = 'Austria';
    public const COUNTRY_AZERBAIJAN = 'Azerbaijan';
    public const COUNTRY_BAHAMAS = 'Bahamas';
    public const COUNTRY_BAHRAIN = 'Bahrain';
    public const COUNTRY_BANGLADESH = 'Bangladesh';
    public const COUNTRY_BARBADOS = 'Barbados';
    public const COUNTRY_BELARUS = 'Belarus';
    public const COUNTRY_BELGIUM = 'Belgium';
    public const COUNTRY_BELIZE = 'Belize';
    public const COUNTRY_BENIN = 'Benin';
    public const COUNTRY_BERMUDA = 'Bermuda';
    public const COUNTRY_BHUTAN = 'Bhutan';
    public const COUNTRY_BOLIVIA = 'Bolivia';
    public const COUNTRY_BOSNIA_HERZEGOVINA = 'Bosnia-Herzegovina';
    public const COUNTRY_BOTSWANA = 'Botswana';
    public const COUNTRY_BRAZIL = 'Brazil';
    public const COUNTRY_BRITISH_INDIAN_OCEAN_TERRITORY = 'British Indian Ocean Territory';
    public const COUNTRY_BRUNEI = 'Brunei';
    public const COUNTRY_BULGARIA = 'Bulgaria';
    public const COUNTRY_BURKINA_FASO = 'Burkina Faso';
    public const COUNTRY_BURMA = 'Burma';
    public const COUNTRY_BURUNDI = 'Burundi';
    public const COUNTRY_CAMBODIA = 'Cambodia';
    public const COUNTRY_CAMEROON = 'Cameroon';
    public const COUNTRY_CANTONAND_ENDERBURY_ISLANDS = 'Canton and Enderbury Islands';
    public const COUNTRY_CAPE_VERDE = 'Cape Verde';
    public const COUNTRY_CAYMAN_ISLANDS = 'Cayman Islands';
    public const COUNTRY_CENTRAL_AFRICAN_REPUBLIC = 'Central African Republic';
    public const COUNTRY_CHAD = 'Chad';
    public const COUNTRY_CHILE = 'Chile';
    public const COUNTRY_CHINA = 'China';
    public const COUNTRY_CHRISTMAS_ISLAND = 'Christmas Island';
    public const COUNTRY_COCOS_KEELING_ISLANDS = 'Cocos (Keeling) Islands';
    public const COUNTRY_COLOMBIA = 'Colombia';
    public const COUNTRY_COMOROS = 'Comoros';
    public const COUNTRY_CONGO = 'Congo';
    public const COUNTRY_CONGO_DEMOCRATIC_REPUBLIC = 'Congo, Democratic Republic';
    public const COUNTRY_COOK_ISLANDS = 'Cook Islands';
    public const COUNTRY_COSTA_RICA = 'Costa Rica';
    public const COUNTRY_CTED_IVOIRE = 'Côte d’Ivoire';
    public const COUNTRY_CROATIA = 'Croatia';
    public const COUNTRY_CUBA = 'Cuba';
    public const COUNTRY_CURAAO = 'Curaçao';
    public const COUNTRY_CYPRUS = 'Cyprus';
    public const COUNTRY_CZECH_REPUBLIC = 'Czech Republic';
    public const COUNTRY_DENMARK = 'Denmark';
    public const COUNTRY_DJIBOUTI = 'Djibouti';
    public const COUNTRY_DOMINICA = 'Dominica';
    public const COUNTRY_DOMINICAN_REPUBLIC = 'Dominican Republic';
    public const COUNTRY_DRONNING_MAUD_LAND = 'Dronning Maud Land';
    public const COUNTRY_EAST_TIMOR = 'East Timor';
    public const COUNTRY_ECUADOR = 'Ecuador';
    public const COUNTRY_EGYPT = 'Egypt';
    public const COUNTRY_EL_SALVADOR = 'El Salvador';
    public const COUNTRY_EQUATORIAL_GUINEA = 'Equatorial Guinea';
    public const COUNTRY_ERITREA = 'Eritrea';
    public const COUNTRY_ESTONIA = 'Estonia';
    public const COUNTRY_ETHIOPIA = 'Ethiopia';
    public const COUNTRY_FAEROE_ISLANDS_FROYAR = 'Faeroe Islands (Føroyar)';
    public const COUNTRY_FALKLAND_ISLANDS = 'Falkland Islands';
    public const COUNTRY_FIJI = 'Fiji';
    public const COUNTRY_FINLAND = 'Finland';
    public const COUNTRY_FRANCE = 'France';
    public const COUNTRY_FRENCH_GUIANA = 'French Guiana';
    public const COUNTRY_FRENCH_POLYNESIA = 'French Polynesia';
    public const COUNTRY_GABON = 'Gabon';
    public const COUNTRY_GAMBIA = 'Gambia';
    public const COUNTRY_GEORGIA = 'Georgia';
    public const COUNTRY_GERMANY = 'Germany';
    public const COUNTRY_GHANA = 'Ghana';
    public const COUNTRY_GIBRALTAR = 'Gibraltar';
    public const COUNTRY_GREAT_BRITAIN = 'Great Britain';
    public const COUNTRY_GREECE = 'Greece';
    public const COUNTRY_GREENLAND = 'Greenland';
    public const COUNTRY_GRENADA = 'Grenada';
    public const COUNTRY_GUADELOUPE = 'Guadeloupe';
    public const COUNTRY_GUAM = 'Guam';
    public const COUNTRY_GUATEMALA = 'Guatemala';
    public const COUNTRY_GUERNSEY = 'Guernsey';
    public const COUNTRY_GUINEA_BISSAU = 'Guinea-Bissau';
    public const COUNTRY_GUINEA = 'Guinea';
    public const COUNTRY_GUYANA = 'Guyana';
    public const COUNTRY_HAITI = 'Haiti';
    public const COUNTRY_HEARDAND_MC_DONALD_ISLANDS = 'Heard and McDonald Islands';
    public const COUNTRY_HONDURAS = 'Honduras';
    public const COUNTRY_HONG_KONG = 'Hong Kong';
    public const COUNTRY_HUNGARY = 'Hungary';
    public const COUNTRY_ICELAND = 'Iceland';
    public const COUNTRY_INDIA = 'India';
    public const COUNTRY_INDONESIA = 'Indonesia';
    public const COUNTRY_INTERNATIONAL_MONETARY_FUND = 'International Monetary Fund';
    public const COUNTRY_IRAN = 'Iran';
    public const COUNTRY_IRAQ = 'Iraq';
    public const COUNTRY_ISLEOF_MAN = 'Isle of Man';
    public const COUNTRY_ISRAEL = 'Israel';
    public const COUNTRY_ITALY = 'Italy';
    public const COUNTRY_IVORY_COAST = 'Ivory Coast';
    public const COUNTRY_JAMAICA = 'Jamaica';
    public const COUNTRY_JAPAN = 'Japan';
    public const COUNTRY_JERSEY = 'Jersey';
    public const COUNTRY_JOHNSTON_ISLAND = 'Johnston Island';
    public const COUNTRY_JORDAN = 'Jordan';
    public const COUNTRY_KAMPUCHEA = 'Kampuchea';
    public const COUNTRY_KAZAKHSTAN = 'Kazakhstan';
    public const COUNTRY_KENYA = 'Kenya';
    public const COUNTRY_KIRIBATI = 'Kiribati';
    public const COUNTRY_KOREA_NORTH = 'Korea, North';
    public const COUNTRY_KOREA_SOUTH = 'Korea, South';
    public const COUNTRY_KUWAIT = 'Kuwait';
    public const COUNTRY_KYRGYZSTAN = 'Kyrgyzstan';
    public const COUNTRY_LAOS = 'Laos';
    public const COUNTRY_LATVIA = 'Latvia';
    public const COUNTRY_LEBANON = 'Lebanon';
    public const COUNTRY_LESOTHO = 'Lesotho';
    public const COUNTRY_LIBERIA = 'Liberia';
    public const COUNTRY_LIBYA = 'Libya';
    public const COUNTRY_LIECHTENSTEIN = 'Liechtenstein';
    public const COUNTRY_LITHUANIA = 'Lithuania';
    public const COUNTRY_LUXEMBOURG = 'Luxembourg';
    public const COUNTRY_MACAU = 'Macau';
    public const COUNTRY_MACEDONIA_FORMER_YUG_REP = 'Macedonia (Former Yug. Rep.)';
    public const COUNTRY_MADAGASCAR = 'Madagascar';
    public const COUNTRY_MALAWI = 'Malawi';
    public const COUNTRY_MALAYSIA = 'Malaysia';
    public const COUNTRY_MALDIVES = 'Maldives';
    public const COUNTRY_MALI = 'Mali';
    public const COUNTRY_MALTA = 'Malta';
    public const COUNTRY_MARSHALL_ISLANDS = 'Marshall Islands';
    public const COUNTRY_MARTINIQUE = 'Martinique';
    public const COUNTRY_MAURITANIA = 'Mauritania';
    public const COUNTRY_MAURITIUS = 'Mauritius';
    public const COUNTRY_MAYOTTE = 'Mayotte';
    public const COUNTRY_MICRONESIA = 'Micronesia';
    public const COUNTRY_MIDWAY_ISLANDS = 'Midway Islands';
    public const COUNTRY_MEXICO = 'Mexico';
    public const COUNTRY_MOLDOVA = 'Moldova';
    public const COUNTRY_MONACO = 'Monaco';
    public const COUNTRY_MONGOLIA = 'Mongolia';
    public const COUNTRY_MONTENEGRO = 'Montenegro';
    public const COUNTRY_MONTSERRAT = 'Montserrat';
    public const COUNTRY_MOROCCO = 'Morocco';
    public const COUNTRY_MOZAMBIQUE = 'Mozambique';
    public const COUNTRY_MYANMAR = 'Myanmar';
    public const COUNTRY_NAURU = 'Nauru';
    public const COUNTRY_NAMIBIA = 'Namibia';
    public const COUNTRY_NEPAL = 'Nepal';
    public const COUNTRY_NETHERLANDS_ANTILLES = 'Netherlands Antilles';
    public const COUNTRY_NETHERLANDS = 'Netherlands';
    public const COUNTRY_NEW_CALEDONIA = 'New Caledonia';
    public const COUNTRY_NEW_ZEALAND = 'New Zealand';
    public const COUNTRY_NICARAGUA = 'Nicaragua';
    public const COUNTRY_NIGER = 'Niger';
    public const COUNTRY_NIGERIA = 'Nigeria';
    public const COUNTRY_NIUE = 'Niue';
    public const COUNTRY_NORFOLK_ISLAND = 'Norfolk Island';
    public const COUNTRY_NORTHERN_MARIANA_ISLANDS = 'Northern Mariana Islands';
    public const COUNTRY_NORWAY = 'Norway';
    public const COUNTRY_OMAN = 'Oman';
    public const COUNTRY_PAKISTAN = 'Pakistan';
    public const COUNTRY_PALAU = 'Palau';
    public const COUNTRY_PALESTINE = 'Palestine';
    public const COUNTRY_PANAMA = 'Panama';
    public const COUNTRY_PAPUA_NEW_GUINEA = 'Papua New Guinea';
    public const COUNTRY_PARAGUAY = 'Paraguay';
    public const COUNTRY_PERU = 'Peru';
    public const COUNTRY_PHILIPPINES = 'Philippines';
    public const COUNTRY_PITCAIRN_ISLAND = 'Pitcairn Island';
    public const COUNTRY_POLAND = 'Poland';
    public const COUNTRY_PUERTO_RICO = 'Puerto Rico';
    public const COUNTRY_QATAR = 'Qatar';
    public const COUNTRY_REUNION = 'Reunion';
    public const COUNTRY_ROMANIA = 'Romania';
    public const COUNTRY_RUSSIA = 'Russia';
    public const COUNTRY_RWANDA = 'Rwanda';
    public const COUNTRY_SAMOA_WESTERN = 'Samoa (Western)';
    public const COUNTRY_SAMOA_AMERICA = 'Samoa (America)';
    public const COUNTRY_SAN_MARINO = 'San Marino';
    public const COUNTRY_SO_TOMAND_PRNCIPE = 'São Tomé and Príncipe';
    public const COUNTRY_SAUDI_ARABIA = 'Saudi Arabia';
    public const COUNTRY_SNGAL = 'Sénégal';
    public const COUNTRY_SERBIA = 'Serbia';
    public const COUNTRY_SEYCHELLES = 'Seychelles';
    public const COUNTRY_SIERRA_LEONE = 'Sierra Leone';
    public const COUNTRY_SINGAPORE = 'Singapore';
    public const COUNTRY_SLOVAKIA = 'Slovakia';
    public const COUNTRY_SLOVENIA = 'Slovenia';
    public const COUNTRY_SOLOMON_ISLANDS = 'Solomon Islands';
    public const COUNTRY_SOMALIA = 'Somalia';
    public const COUNTRY_SOUTH_AFRICA = 'South Africa';
    public const COUNTRY_SPAIN = 'Spain';
    public const COUNTRY_SRI_LANKA = 'Sri Lanka';
    public const COUNTRY_ST_HELENA = 'St. Helena';
    public const COUNTRY_ST_KITTSAND_NEVIS = 'St. Kitts and Nevis';
    public const COUNTRY_ST_LUCIA = 'St. Lucia';
    public const COUNTRY_ST_VINCENTANDTHE_GRENADINES = 'St. Vincent and the Grenadines';
    public const COUNTRY_SUDAN = 'Sudan';
    public const COUNTRY_SURINAME = 'Suriname';
    public const COUNTRY_SVALBARDAND_JAN_MAYEN_ISLANDS = 'Svalbard and Jan Mayen Islands';
    public const COUNTRY_SWAZILAND = 'Swaziland';
    public const COUNTRY_SWEDEN = 'Sweden';
    public const COUNTRY_SWITZERLAND = 'Switzerland';
    public const COUNTRY_SYRIA = 'Syria';
    public const COUNTRY_TAHITI = 'Tahiti';
    public const COUNTRY_TAIWAN = 'Taiwan';
    public const COUNTRY_TAJIKISTAN = 'Tajikistan';
    public const COUNTRY_TANZANIA = 'Tanzania';
    public const COUNTRY_THAILAND = 'Thailand';
    public const COUNTRY_TIMOR_LESTE = 'Timor-Leste';
    public const COUNTRY_TOGO = 'Togo';
    public const COUNTRY_TRINIDADAND_TOBAGO = 'Trinidad and Tobago';
    public const COUNTRY_TUNISIA = 'Tunisia';
    public const COUNTRY_TURKEY = 'Turkey';
    public const COUNTRY_TURKMENISTAN = 'Turkmenistan';
    public const COUNTRY_TURKSAND_CAICOS_ISLANDS = 'Turks and Caicos Islands';
    public const COUNTRY_TUVALU = 'Tuvalu';
    public const COUNTRY_UGANDA = 'Uganda';
    public const COUNTRY_UKRAINE = 'Ukraine';
    public const COUNTRY_UNITED_ARAB_EMIRATES = 'United Arab Emirates';
    public const COUNTRY_UPPER_VOLTA = 'Upper Volta';
    public const COUNTRY_URUGUAY = 'Uruguay';
    public const COUNTRY_UZBEKISTAN = 'Uzbekistan';
    public const COUNTRY_VANUATU = 'Vanuatu';
    public const COUNTRY_VATICAN = 'Vatican';
    public const COUNTRY_VENEZUELA = 'Venezuela';
    public const COUNTRY_VIETNAM = 'Vietnam';
    public const COUNTRY_VIRGIN_ISLANDS = 'Virgin Islands';
    public const COUNTRY_WAKE_ISLAND = 'Wake Island';
    public const COUNTRY_WALLISAND_FUTUNA_ISLANDS = 'Wallis and Futuna Islands';
    public const COUNTRY_WESTERN_SAHARA = 'Western Sahara';
    public const COUNTRY_WESTERN_SAMOA = 'Western Samoa';
    public const COUNTRY_YEMEN = 'Yemen';
    public const COUNTRY_ZARE = 'Zaïre';
    public const COUNTRY_ZAMBIA = 'Zambia';
    public const COUNTRY_ZIMBABWE = 'Zimbabwe';

    # Simple key value mapping for Countries
    public const COUNTRIES_LIST = [
        self::COUNTRY_PORTUGAL => 'Portugal',
        self::COUNTRY_IRELAND => 'Ireland',
        self::COUNTRY_UK => 'UK',
        self::COUNTRY_CANADA => 'Canada',
        self::COUNTRY_UNITED_STATES => 'United States',
        self::COUNTRY_AFGHANISTAN => 'Afghanistan',
        self::COUNTRY_ALBANIA => 'Albania',
        self::COUNTRY_ALGERIA => 'Algeria',
        self::COUNTRY_AMERICAN_SAMOA => 'American Samoa',
        self::COUNTRY_ANDORRA => 'Andorra',
        self::COUNTRY_ANGOLA => 'Angola',
        self::COUNTRY_ANGUILLA => 'Anguilla',
        self::COUNTRY_ANTIGUAAND_BARBUDA => 'Antigua and Barbuda',
        self::COUNTRY_ARGENTINA => 'Argentina',
        self::COUNTRY_ARMENIA => 'Armenia',
        self::COUNTRY_ARUBA => 'Aruba',
        self::COUNTRY_AUSTRALIA => 'Australia',
        self::COUNTRY_AUSTRIA => 'Austria',
        self::COUNTRY_AZERBAIJAN => 'Azerbaijan',
        self::COUNTRY_BAHAMAS => 'Bahamas',
        self::COUNTRY_BAHRAIN => 'Bahrain',
        self::COUNTRY_BANGLADESH => 'Bangladesh',
        self::COUNTRY_BARBADOS => 'Barbados',
        self::COUNTRY_BELARUS => 'Belarus',
        self::COUNTRY_BELGIUM => 'Belgium',
        self::COUNTRY_BELIZE => 'Belize',
        self::COUNTRY_BENIN => 'Benin',
        self::COUNTRY_BERMUDA => 'Bermuda',
        self::COUNTRY_BHUTAN => 'Bhutan',
        self::COUNTRY_BOLIVIA => 'Bolivia',
        self::COUNTRY_BOSNIA_HERZEGOVINA => 'Bosnia-Herzegovina',
        self::COUNTRY_BOTSWANA => 'Botswana',
        self::COUNTRY_BRAZIL => 'Brazil',
        self::COUNTRY_BRITISH_INDIAN_OCEAN_TERRITORY => 'British Indian Ocean Territory',
        self::COUNTRY_BRUNEI => 'Brunei',
        self::COUNTRY_BULGARIA => 'Bulgaria',
        self::COUNTRY_BURKINA_FASO => 'Burkina Faso',
        self::COUNTRY_BURMA => 'Burma',
        self::COUNTRY_BURUNDI => 'Burundi',
        self::COUNTRY_CAMBODIA => 'Cambodia',
        self::COUNTRY_CAMEROON => 'Cameroon',
        self::COUNTRY_CANTONAND_ENDERBURY_ISLANDS => 'Canton and Enderbury Islands',
        self::COUNTRY_CAPE_VERDE => 'Cape Verde',
        self::COUNTRY_CAYMAN_ISLANDS => 'Cayman Islands',
        self::COUNTRY_CENTRAL_AFRICAN_REPUBLIC => 'Central African Republic',
        self::COUNTRY_CHAD => 'Chad',
        self::COUNTRY_CHILE => 'Chile',
        self::COUNTRY_CHINA => 'China',
        self::COUNTRY_CHRISTMAS_ISLAND => 'Christmas Island',
        self::COUNTRY_COCOS_KEELING_ISLANDS => 'Cocos (Keeling) Islands',
        self::COUNTRY_COLOMBIA => 'Colombia',
        self::COUNTRY_COMOROS => 'Comoros',
        self::COUNTRY_CONGO => 'Congo',
        self::COUNTRY_CONGO_DEMOCRATIC_REPUBLIC => 'Congo, Democratic Republic',
        self::COUNTRY_COOK_ISLANDS => 'Cook Islands',
        self::COUNTRY_COSTA_RICA => 'Costa Rica',
        self::COUNTRY_CTED_IVOIRE => 'Côte d’Ivoire',
        self::COUNTRY_CROATIA => 'Croatia',
        self::COUNTRY_CUBA => 'Cuba',
        self::COUNTRY_CURAAO => 'Curaçao',
        self::COUNTRY_CYPRUS => 'Cyprus',
        self::COUNTRY_CZECH_REPUBLIC => 'Czech Republic',
        self::COUNTRY_DENMARK => 'Denmark',
        self::COUNTRY_DJIBOUTI => 'Djibouti',
        self::COUNTRY_DOMINICA => 'Dominica',
        self::COUNTRY_DOMINICAN_REPUBLIC => 'Dominican Republic',
        self::COUNTRY_DRONNING_MAUD_LAND => 'Dronning Maud Land',
        self::COUNTRY_EAST_TIMOR => 'East Timor',
        self::COUNTRY_ECUADOR => 'Ecuador',
        self::COUNTRY_EGYPT => 'Egypt',
        self::COUNTRY_EL_SALVADOR => 'El Salvador',
        self::COUNTRY_EQUATORIAL_GUINEA => 'Equatorial Guinea',
        self::COUNTRY_ERITREA => 'Eritrea',
        self::COUNTRY_ESTONIA => 'Estonia',
        self::COUNTRY_ETHIOPIA => 'Ethiopia',
        self::COUNTRY_FAEROE_ISLANDS_FROYAR => 'Faeroe Islands (Føroyar)',
        self::COUNTRY_FALKLAND_ISLANDS => 'Falkland Islands',
        self::COUNTRY_FIJI => 'Fiji',
        self::COUNTRY_FINLAND => 'Finland',
        self::COUNTRY_FRANCE => 'France',
        self::COUNTRY_FRENCH_GUIANA => 'French Guiana',
        self::COUNTRY_FRENCH_POLYNESIA => 'French Polynesia',
        self::COUNTRY_GABON => 'Gabon',
        self::COUNTRY_GAMBIA => 'Gambia',
        self::COUNTRY_GEORGIA => 'Georgia',
        self::COUNTRY_GERMANY => 'Germany',
        self::COUNTRY_GHANA => 'Ghana',
        self::COUNTRY_GIBRALTAR => 'Gibraltar',
        self::COUNTRY_GREAT_BRITAIN => 'Great Britain',
        self::COUNTRY_GREECE => 'Greece',
        self::COUNTRY_GREENLAND => 'Greenland',
        self::COUNTRY_GRENADA => 'Grenada',
        self::COUNTRY_GUADELOUPE => 'Guadeloupe',
        self::COUNTRY_GUAM => 'Guam',
        self::COUNTRY_GUATEMALA => 'Guatemala',
        self::COUNTRY_GUERNSEY => 'Guernsey',
        self::COUNTRY_GUINEA_BISSAU => 'Guinea-Bissau',
        self::COUNTRY_GUINEA => 'Guinea',
        self::COUNTRY_GUYANA => 'Guyana',
        self::COUNTRY_HAITI => 'Haiti',
        self::COUNTRY_HEARDAND_MC_DONALD_ISLANDS => 'Heard and McDonald Islands',
        self::COUNTRY_HONDURAS => 'Honduras',
        self::COUNTRY_HONG_KONG => 'Hong Kong',
        self::COUNTRY_HUNGARY => 'Hungary',
        self::COUNTRY_ICELAND => 'Iceland',
        self::COUNTRY_INDIA => 'India',
        self::COUNTRY_INDONESIA => 'Indonesia',
        self::COUNTRY_INTERNATIONAL_MONETARY_FUND => 'International Monetary Fund',
        self::COUNTRY_IRAN => 'Iran',
        self::COUNTRY_IRAQ => 'Iraq',
        self::COUNTRY_ISLEOF_MAN => 'Isle of Man',
        self::COUNTRY_ISRAEL => 'Israel',
        self::COUNTRY_ITALY => 'Italy',
        self::COUNTRY_IVORY_COAST => 'Ivory Coast',
        self::COUNTRY_JAMAICA => 'Jamaica',
        self::COUNTRY_JAPAN => 'Japan',
        self::COUNTRY_JERSEY => 'Jersey',
        self::COUNTRY_JOHNSTON_ISLAND => 'Johnston Island',
        self::COUNTRY_JORDAN => 'Jordan',
        self::COUNTRY_KAMPUCHEA => 'Kampuchea',
        self::COUNTRY_KAZAKHSTAN => 'Kazakhstan',
        self::COUNTRY_KENYA => 'Kenya',
        self::COUNTRY_KIRIBATI => 'Kiribati',
        self::COUNTRY_KOREA_NORTH => 'Korea, North',
        self::COUNTRY_KOREA_SOUTH => 'Korea, South',
        self::COUNTRY_KUWAIT => 'Kuwait',
        self::COUNTRY_KYRGYZSTAN => 'Kyrgyzstan',
        self::COUNTRY_LAOS => 'Laos',
        self::COUNTRY_LATVIA => 'Latvia',
        self::COUNTRY_LEBANON => 'Lebanon',
        self::COUNTRY_LESOTHO => 'Lesotho',
        self::COUNTRY_LIBERIA => 'Liberia',
        self::COUNTRY_LIBYA => 'Libya',
        self::COUNTRY_LIECHTENSTEIN => 'Liechtenstein',
        self::COUNTRY_LITHUANIA => 'Lithuania',
        self::COUNTRY_LUXEMBOURG => 'Luxembourg',
        self::COUNTRY_MACAU => 'Macau',
        self::COUNTRY_MACEDONIA_FORMER_YUG_REP => 'Macedonia (Former Yug. Rep.)',
        self::COUNTRY_MADAGASCAR => 'Madagascar',
        self::COUNTRY_MALAWI => 'Malawi',
        self::COUNTRY_MALAYSIA => 'Malaysia',
        self::COUNTRY_MALDIVES => 'Maldives',
        self::COUNTRY_MALI => 'Mali',
        self::COUNTRY_MALTA => 'Malta',
        self::COUNTRY_MARSHALL_ISLANDS => 'Marshall Islands',
        self::COUNTRY_MARTINIQUE => 'Martinique',
        self::COUNTRY_MAURITANIA => 'Mauritania',
        self::COUNTRY_MAURITIUS => 'Mauritius',
        self::COUNTRY_MAYOTTE => 'Mayotte',
        self::COUNTRY_MICRONESIA => 'Micronesia',
        self::COUNTRY_MIDWAY_ISLANDS => 'Midway Islands',
        self::COUNTRY_MEXICO => 'Mexico',
        self::COUNTRY_MOLDOVA => 'Moldova',
        self::COUNTRY_MONACO => 'Monaco',
        self::COUNTRY_MONGOLIA => 'Mongolia',
        self::COUNTRY_MONTENEGRO => 'Montenegro',
        self::COUNTRY_MONTSERRAT => 'Montserrat',
        self::COUNTRY_MOROCCO => 'Morocco',
        self::COUNTRY_MOZAMBIQUE => 'Mozambique',
        self::COUNTRY_MYANMAR => 'Myanmar',
        self::COUNTRY_NAURU => 'Nauru',
        self::COUNTRY_NAMIBIA => 'Namibia',
        self::COUNTRY_NEPAL => 'Nepal',
        self::COUNTRY_NETHERLANDS_ANTILLES => 'Netherlands Antilles',
        self::COUNTRY_NETHERLANDS => 'Netherlands',
        self::COUNTRY_NEW_CALEDONIA => 'New Caledonia',
        self::COUNTRY_NEW_ZEALAND => 'New Zealand',
        self::COUNTRY_NICARAGUA => 'Nicaragua',
        self::COUNTRY_NIGER => 'Niger',
        self::COUNTRY_NIGERIA => 'Nigeria',
        self::COUNTRY_NIUE => 'Niue',
        self::COUNTRY_NORFOLK_ISLAND => 'Norfolk Island',
        self::COUNTRY_NORTHERN_MARIANA_ISLANDS => 'Northern Mariana Islands',
        self::COUNTRY_NORWAY => 'Norway',
        self::COUNTRY_OMAN => 'Oman',
        self::COUNTRY_PAKISTAN => 'Pakistan',
        self::COUNTRY_PALAU => 'Palau',
        self::COUNTRY_PALESTINE => 'Palestine',
        self::COUNTRY_PANAMA => 'Panama',
        self::COUNTRY_PAPUA_NEW_GUINEA => 'Papua New Guinea',
        self::COUNTRY_PARAGUAY => 'Paraguay',
        self::COUNTRY_PERU => 'Peru',
        self::COUNTRY_PHILIPPINES => 'Philippines',
        self::COUNTRY_PITCAIRN_ISLAND => 'Pitcairn Island',
        self::COUNTRY_POLAND => 'Poland',
        self::COUNTRY_PUERTO_RICO => 'Puerto Rico',
        self::COUNTRY_QATAR => 'Qatar',
        self::COUNTRY_REUNION => 'Reunion',
        self::COUNTRY_ROMANIA => 'Romania',
        self::COUNTRY_RUSSIA => 'Russia',
        self::COUNTRY_RWANDA => 'Rwanda',
        self::COUNTRY_SAMOA_WESTERN => 'Samoa (Western)',
        self::COUNTRY_SAMOA_AMERICA => 'Samoa (America)',
        self::COUNTRY_SAN_MARINO => 'San Marino',
        self::COUNTRY_SO_TOMAND_PRNCIPE => 'São Tomé and Príncipe',
        self::COUNTRY_SAUDI_ARABIA => 'Saudi Arabia',
        self::COUNTRY_SNGAL => 'Sénégal',
        self::COUNTRY_SERBIA => 'Serbia',
        self::COUNTRY_SEYCHELLES => 'Seychelles',
        self::COUNTRY_SIERRA_LEONE => 'Sierra Leone',
        self::COUNTRY_SINGAPORE => 'Singapore',
        self::COUNTRY_SLOVAKIA => 'Slovakia',
        self::COUNTRY_SLOVENIA => 'Slovenia',
        self::COUNTRY_SOLOMON_ISLANDS => 'Solomon Islands',
        self::COUNTRY_SOMALIA => 'Somalia',
        self::COUNTRY_SOUTH_AFRICA => 'South Africa',
        self::COUNTRY_SPAIN => 'Spain',
        self::COUNTRY_SRI_LANKA => 'Sri Lanka',
        self::COUNTRY_ST_HELENA => 'St. Helena',
        self::COUNTRY_ST_KITTSAND_NEVIS => 'St. Kitts and Nevis',
        self::COUNTRY_ST_LUCIA => 'St. Lucia',
        self::COUNTRY_ST_VINCENTANDTHE_GRENADINES => 'St. Vincent and the Grenadines',
        self::COUNTRY_SUDAN => 'Sudan',
        self::COUNTRY_SURINAME => 'Suriname',
        self::COUNTRY_SVALBARDAND_JAN_MAYEN_ISLANDS => 'Svalbard and Jan Mayen Islands',
        self::COUNTRY_SWAZILAND => 'Swaziland',
        self::COUNTRY_SWEDEN => 'Sweden',
        self::COUNTRY_SWITZERLAND => 'Switzerland',
        self::COUNTRY_SYRIA => 'Syria',
        self::COUNTRY_TAHITI => 'Tahiti',
        self::COUNTRY_TAIWAN => 'Taiwan',
        self::COUNTRY_TAJIKISTAN => 'Tajikistan',
        self::COUNTRY_TANZANIA => 'Tanzania',
        self::COUNTRY_THAILAND => 'Thailand',
        self::COUNTRY_TIMOR_LESTE => 'Timor-Leste',
        self::COUNTRY_TOGO => 'Togo',
        self::COUNTRY_TRINIDADAND_TOBAGO => 'Trinidad and Tobago',
        self::COUNTRY_TUNISIA => 'Tunisia',
        self::COUNTRY_TURKEY => 'Turkey',
        self::COUNTRY_TURKMENISTAN => 'Turkmenistan',
        self::COUNTRY_TURKSAND_CAICOS_ISLANDS => 'Turks and Caicos Islands',
        self::COUNTRY_TUVALU => 'Tuvalu',
        self::COUNTRY_UGANDA => 'Uganda',
        self::COUNTRY_UKRAINE => 'Ukraine',
        self::COUNTRY_UNITED_ARAB_EMIRATES => 'United Arab Emirates',
        self::COUNTRY_UPPER_VOLTA => 'Upper Volta',
        self::COUNTRY_URUGUAY => 'Uruguay',
        self::COUNTRY_UZBEKISTAN => 'Uzbekistan',
        self::COUNTRY_VANUATU => 'Vanuatu',
        self::COUNTRY_VATICAN => 'Vatican',
        self::COUNTRY_VENEZUELA => 'Venezuela',
        self::COUNTRY_VIETNAM => 'Vietnam',
        self::COUNTRY_VIRGIN_ISLANDS => 'Virgin Islands',
        self::COUNTRY_WAKE_ISLAND => 'Wake Island',
        self::COUNTRY_WALLISAND_FUTUNA_ISLANDS => 'Wallis and Futuna Islands',
        self::COUNTRY_WESTERN_SAHARA => 'Western Sahara',
        self::COUNTRY_WESTERN_SAMOA => 'Western Samoa',
        self::COUNTRY_YEMEN => 'Yemen',
        self::COUNTRY_ZARE => 'Zaïre',
        self::COUNTRY_ZAMBIA => 'Zambia',
        self::COUNTRY_ZIMBABWE => 'Zimbabwe',
    ];

}